services:
  - type: web
    name: sono-sghair-api
    runtime: python
    buildCommand: pip install -r requirements.txt
    startCommand: uvicorn app.main:app --host 0.0.0.0 --port $PORT
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.9
      - key: DATABASE_URL
        fromDatabase:
          name: sono-db
          property: connectionString

databases:
  - name: sono-db
    plan: free
